version: "3"

services:
  db:
    image: hub.hamdocker.ir/library/postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword


  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    volumes:
      - .:/tmp
    ports:
      - "8888:8888"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      REDIS_HOST: redis
      REDIS_PORT: 6379
    
    tty: true
volumes:
  db:
    driver: local