# Generated by Django 4.1.7 on 2023-04-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_score_avg_product_vote_alter_score_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='score_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='vote',
            field=models.FloatField(default=0),
        ),
    ]
