# Generated by Django 4.1.7 on 2023-04-19 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0008_remove_authtoken_salt'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomeAuthToken',
            fields=[
                ('authtoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knox.authtoken')),
                ('user_agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.useragent')),
            ],
            bases=('knox.authtoken',),
        ),
    ]
