# Generated by Django 4.1.7 on 2023-04-26 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cart_open_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cart',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.cart'),
            preserve_default=False,
        ),
    ]
