# Generated by Django 4.1.7 on 2023-04-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_track_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.UUIDField(default='a21b213c53d64da4afee5178e3db5694', editable=False, unique=True),
        ),
    ]
