# Generated by Django 4.1.7 on 2023-04-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_track_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.UUIDField(default='28b4646a909a456a844425c26a396ff9', editable=False, unique=True),
        ),
    ]
