# Generated by Django 4.1.7 on 2023-04-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_track_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.UUIDField(default='3755495bd13243c7a3be6dac2164486c', editable=False, unique=True),
        ),
    ]
