# Generated by Django 4.1.7 on 2023-04-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_track_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.UUIDField(default='7b30ff3b51844b499147416913e87195', editable=False, unique=True),
        ),
    ]
