# Generated by Django 4.1.7 on 2023-04-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_track_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.UUIDField(default='0959e496c1f043f8a3aadb64bc79bb45', editable=False, unique=True),
        ),
    ]
