# Generated by Django 4.1.7 on 2023-04-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_track_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='open',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.UUIDField(default='adcbcbec7e8648978c9f2b879ac47dcd', editable=False, unique=True),
        ),
    ]
