# Generated by Django 4.1.7 on 2023-04-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_cart_open_alter_track_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.UUIDField(default='5a8f432bfe9f49b0a6d8f20e0059a12a', editable=False, unique=True),
        ),
    ]
