# Generated by Django 4.1.7 on 2023-04-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_track_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.UUIDField(default='00c03e2ea3774723a73bb1dfef155e6b', editable=False, unique=True),
        ),
    ]
