# Generated by Django 4.1.7 on 2023-04-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_cart_open_alter_track_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.UUIDField(default='b19e894b1ce945519f0d2fc7b39a1b35', editable=False, unique=True),
        ),
    ]
