# Generated by Django 4.1.7 on 2023-04-30 13:30

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_track_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.CharField(default=order.models.uid, editable=False, max_length=64, unique=True),
        ),
    ]
